    indent = 4
    margin = 80
    always_for_in = false
    whitespace_typedefs = false
    whitespace_ops_in_indices = false
    remove_extra_newlines = true
    import_to_using = true
    pipe_to_function_call = true
    short_to_long_function_def = true
    always_use_return = true
    whitespace_in_kwargs = true
    annotate_untyped_fields_with_any = true
    format_docstrings = true
    align_struct_field = true
    align_conditional = true
    align_assignment = true
    align_pair_arrow = true
    conditional_to_if = false
    normalize_line_endings = "unix"