name = "GraphMatFun"
uuid = "456a00ab-810a-4bbb-9f06-6bc08c0a1e82"
authors = ["Elias Jarlebring <jarlebring@gmail.com> and contributors"]
version = "0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
GenericLinearAlgebra = "0.2"
Polynomials = "1.2"
Roots = "1.0, 2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
